apiVersion: v1
kind: PersistenceVolume
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  storageClassName: my-storage-class
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mydata"