apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 2Gi  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain    
  nfs:
    path: /storage
    server: 172.22.28.6
    readOnly: false